#!/usr/bin/env bash
#===============================================================================
#
# pu_depgen.sh: Utility script to generage GNU make depfiles from plantuml
#               "!include" statements.
#
#===============================================================================

SED="${SED:-"$( command -v sed )"}"

# Recursively get IUML dependencies:
# $1 == file to read
function __get_iuml_deps() {
    log_debug "Getting iuml deps for \"$1\""
    local -a pu_deps
    pu_deps=($(${SED} -n 's/^!include\s*\(.*\)/\1/p' ${1}))

    local pu_dep
    for pu_dep in ${pu_deps[@]}; do
        pu_deps+=($(__get_iuml_deps "${pu_dep}"))
    done
    echo "${pu_deps[@]}"
}

# Generate makefile dependency information for the given file.
function __gen_deps() {
    log_debug "Generating deps for \"$1\""
    local file_path target
    local -a deps
    file_path="${1}" ; shift

    target="$( ${SED} 's/\.pu/\.svg/' <<< "${file_path}")"
    deps=($( __get_iuml_deps ${file_path} ))

    echo "${target}: ${deps[@]}"
}

# Write out the dependency header:
cat <<EOF
#---------------------------------------------------------------------
# Plantuml dependencies for ${PWD##*/}
# Generated: $(date)
#
# NOTE: Do not edit this file by hand! Changes will be overwritten
#       by next "make" invocation.
#---------------------------------------------------------------------

EOF

# Iterate over each dependency, generating an entry with prerequisites:
function output_deps() {
    local IFS=$'\n'
    for s in $(find ./ -type f -name "*.pu"); do
        __gen_deps "${s}"
    done

    echo -e "\n# END Auto-generated Dependencies\n"
}

#print_var "PWD"
#print_var "PU_ROOT"

output_deps "$@"

# EOF

